/*
 * Defines.h
 *
 *  Created on: Oct 23, 2022
 *      Author: marce
 */

#ifndef SRC_APPMAIN_DEFINES_H_
#define SRC_APPMAIN_DEFINES_H_

#define GEAR_RATIO			1
#define CURRENT_2_TORQUE	1



#define SEND_SETTINGS		0x01
#define SEND_COMMAND		0x02
#define SEND_STATUS			0x03

#define GET_SETTINGS		0x11
#define GET_COMMAND			0x12
#define GET_STATUS			0x13

//Address
#define CLOSE_ADDR					0x01
#define OPEN_ADDR					0x02
#define TEACH_ADDR					0x03
#define RESET_ADDR					0x04
#define ENABLE_ADDR					0x05

#define STOP_ADDR					0x07
#define ERROR_ADDR					0x08
#define STATUS_ADDR					0x09

#define TEACH_TORQUE_ADDR			0x10
#define TEACH_SPEED_ADDR			0x11

#define CLAMPING_TORQUE_ADDR		0x12
#define CLAMPING_SPEED_ADDR			0x13

#define SELF_SHUTDOWN_DELAY_ADDR	0x14
#define IN_POS_DIFF_ADDR			0x15
#define OPENING_DISTANCE_ADDR		0x16

#define UNDERVOLTAGE_WARNING_ADDR	0x17
#define UNDERVOLTAGE_ERROR_ADDR		0x18

#define OVER_CURRENT_WARNING_ADDR	0x19
#define OVER_CURRENT_ERROR_ADDR		0x1A

#define DEVICE_ADDRESS_ADDR			0x20


#define RCV_STATUS			0xAA




#define EXT_LED_SET 		HAL_GPIO_WritePin(LED_EXT_GPIO_Port, LED_EXT_Pin, GPIO_PIN_SET)
#define EXT_LED_RESET 		HAL_GPIO_WritePin(LED_EXT_GPIO_Port, LED_EXT_Pin, GPIO_PIN_RESET)

#define LED_SET 			HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_SET)
#define LED_RESET 			HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET)

#define POWER_FET_SET 	 	HAL_GPIO_WritePin(POWER_SWITCH_GPIO_Port, POWER_SWITCH_Pin, GPIO_PIN_SET)
#define POWER_FET_RESET 	HAL_GPIO_WritePin(POWER_SWITCH_GPIO_Port, POWER_SWITCH_Pin, GPIO_PIN_RESET)

#define IS_EXT_SWITCH		HAL_GPIO_ReadPin(SW_EXT_GPIO_Port, SW_EXT_Pin)

//general settings

#define DIRECTION_IN	3200
#define DIRECTION_OUT	6400



#endif /* SRC_APPMAIN_DEFINES_H_ */
