namespace Schraubstock_v2.Adresses;

public enum RegisterAdress : byte
{
    ERROR_ADDR = 0x28,
    TEACH_TORQUE_ADDR = 0x29,
    TEACH_SPEED_ADDR = 0x2A,
    CLAMPING_TORQUE_ADDR = 0x2B,
    CLAMPING_SPEED_ADDR = 0x2C,
    SELF_SHUTDOWN_DELAY_ADDR = 0x2D,
    IN_POS_DIFF_ADDR = 0x2E,
    OPENING_DISTANCE_ADDR = 0x2F,
    UNDERVOLTAGE_WARNING_ADDR = 0x30,
    UNDERVOLTAGE_ERROR_ADDR = 0x31,
    OVER_CURRENT_WARNING_ADDR = 0x32,
    OVER_CURRENT_ERROR_ADDR = 0x33,
    DEVICE_ADDRESS_ADDR = 0x34,
    SAVE_SETTINGS_ADDR = 0x55
}
